### ISSUE TITLE
What the hell is this game?

### ISSUE THREAD

**Issue by bmceldowney** [bmceldowney/TheGame#1]
We should figure out what this thing is.

There's an interesting planning tool where I've set up a project.

https://app.hacknplan.com/

**Comment by bmceldowney** [comment]
It could be a simple platformer. Scrolling to the left (or what if it scrolled to the right?). Vertical platformers (up or down) are also potential candidates.

**Comment by bmceldowney** [comment]
It could also be a puzzle game. Match 3 is pretty popular, though by no means the only option.

**Comment by bmceldowney** [comment]
It could be an RPG. It would be a lot of work and we wouldn't get anywhere near a Dragon Age or anything, but we could probably come pretty close to a [Pixel Dungeon](http://pixeldungeon.watabou.ru/).

**Comment by angellmethod** [comment]
I like the idea of an RPG or tower defense w/ upgradable towers or a champion that can do stuff!

Did you ever play Castle of the Winds? 

https://classicreload.com/castle-or-the-winds.html

**Comment by bmceldowney** [comment]
I have not played it yet but I have watched a few let's plays on YouTube. I think we can definitely shoot for an RPG.

**Comment by bmceldowney** [comment]
Answer:

This game is going to be an RPG!
